apiVersion: v1
kind: Secret
metadata:
  name: seafile-secret
type: Opaque
data:
  # for Seafile server
  JWT_PRIVATE_KEY: "<your JWT key, can generate from `pwgen -s 40 1`>"

  # for database
  SEAFILE_MYSQL_DB_PASSWORD: "<MySQL user seafile's passsword>"

  # Initialization
  ## for db
  INIT_SEAFILE_MYSQL_ROOT_PASSWORD: "<MySQL user root's password>"

  ## For S3 storage backend (only valid in INIT_S3_STORAGE_BACKEND_CONFIG = true)
  INIT_S3_SECRET_KEY: ""